### ISSUE TITLE
Are Item IDs required to be unique across multiple collections?

### ISSUE THREAD

**Issue by pedro-cf** [Healy-Hyperspatial/stac-fastapi-mongo#25]
Greetings, are Item IDs required to be unique across multiple collections?

Currently this is enforced based on this index:
https://github.com/Healy-Hyperspatial/stac-fastapi-mongo/blob/e06e1769e80b438c34cc52910baab95f5e828726/stac_fastapi/mongo/database_logic.py#L78

Can you confirm @jonhealy1 ?

If not I would like to change this line to:

```python
await collection.create_index([("collection", 1), ("id", 1)], unique=True)
```

Not sure if this is the also the case for https://github.com/stac-utils/stac-fastapi-elasticsearch-opensearch

**Comment by jonhealy1** [comment]
Hi. I don't think item ids should be unique across collections.

**Comment by jonhealy1** [comment]
[Here](https://github.com/stac-utils/stac-fastapi-elasticsearch-opensearch/blob/ee365ab81d992e156bfb13cc7c75acb5da939820/stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/database_logic.py#L851-L858) in sfeos, the id is being created from both the item id and the collection id.

**Comment by pedro-cf** [comment]
> [Here](https://github.com/stac-utils/stac-fastapi-elasticsearch-opensearch/blob/ee365ab81d992e156bfb13cc7c75acb5da939820/stac_fastapi/elasticsearch/stac_fastapi/elasticsearch/database_logic.py#L851-L858) in sfeos, the id is being created from both the item id and the collection id.

awesome so it's not an issue for sfeos, thank you
