### ISSUE TITLE
"read-only" DB mode, and optional index creation

### ISSUE THREAD

**Issue by GorgiAstro** [Healy-Hyperspatial/stac-fastapi-mongo#28]
Hi, 

First of all thanks for the awesome mongo backend. 

Is it possible to have a mode where the MongoDB is not written? For safety reasons I am using stac_fastapi_mongo with a read-only MongoDB user.
The only issue I have is the calls `create_collection_index()` and `create_item_index()` which I had to comment out, otherwise it causes an error because of my read-only MongoDB user. I don't need to create these MongoDB indexes because my software which feeds data into the MongoDB already takes care of it, so it would be nice to make this optional.

**Comment by jonhealy1** [comment]
Hi. Nice to hear from you. Would you be able to create a pr for this issue?

**Comment by GorgiAstro** [comment]
Yes I can. Is it okay to enable/disable the two calls `create_collection_index()` and `create_item_index()` using an environment variable (with the default value being the current behaviour, i.e. performing these two calls)?

**Comment by jonhealy1** [comment]
Hi @GorgiAstro sounds good! Thank you

**Comment by GorgiAstro** [comment]
I opened a PR: https://github.com/Healy-Hyperspatial/stac-fastapi-mongo/pull/31

**Comment by GorgiAstro** [comment]
Closed by #31
