### ISSUE TITLE
Basic Authentication

### ISSUE THREAD

**Issue by pedro-cf** [Healy-Hyperspatial/stac-fastapi-mongo#8]
Greetings,

How can I configure Basic Authentication when deploying this project ?

**Comment by jonhealy1** [comment]
Hi. There are a couple of options for setting up authentication: through your cloud provider or directly at the application level by using FastAPI. It’s worth noting that stac-fastapi doesn’t directly offer guidelines for implementing authentication. We've had discussions on this, and the consensus leans towards leaving it to individual implementations to accommodate various use-cases.

**Comment by jonhealy1** [comment]
It might be worth having a discussion here: https://github.com/stac-utils/stac-fastapi-elasticsearch-opensearch. This is the home of the core library used for this project and it's a project that has been used in real-world applications.
